version: '3'

services:
  mysql:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    expose:
      - 3306
      - 33060
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
    expose:
      - 80
    ports:
      - 80
    links:
      - mysql:mysql

  mysql-tools:
    build: .
    image: mysql-tools
    command: adduser % testing
    environment:
      - MYSQL_HOST=mysql
    links:
      - mysql:mysql
    depends_on:
      - mysql
